import {StyleSheet} from 'react-native';
import {color} from '../../ui-kit/styles/color';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
    flexDirection: 'column',
  },
  headerContainer: {
    flexDirection: 'row',
    marginTop: 35,
    justifyContent: 'space-between',
    marginHorizontal: 30,
  },
  balanceContainer: {
    alignSelf: 'center',
    marginTop: 15,
    marginHorizontal: 30,
    width: 315,
    height: 170,
  },
  balanceText: {
    fontSize: 13,
    fontWeight: 'regular',
    color: color.bText,
    alignSelf: 'center',
    marginTop: 30,
  },
  balanceAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: color.bText,
    alignSelf: 'center',
    marginTop: 12.5,
  },
  balanceProgress: {
    borderRadius: 10,
    alignSelf: 'center',
    width: 222,
    marginTop: 10,
  },
  balanceLimit: {
    fontSize: 10,
    fontWeight: 'medium',
    color: color.bText,
    alignSelf: 'center',
    marginTop: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 50,
    marginTop: 30,
    marginBottom: 39,
  },
  block: {
    backgroundColor: color.block,
    width: '100%',
    height: 445,
  },
  welcomeText: {
    fontSize: 13,
    color: color.hText,
    marginBottom: 5,
  },
  name: {
    fontSize: 18,
    fontWeight: 'bold',
    color: color.hText,
  },
  photo: {
    marginTop: 6,
    width: 40,
    height: 40,
  },
  image: {
    alignSelf: 'center',
    marginTop: 15,
    marginHorizontal: 30,
    width: 315,
    height: 170,
  },
  bIcon: {
    width: 24,
    height: 24,
  },
  button: {
    width: 145,
    height: 60,
    borderRadius: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: color.hButton,
  },
  buttonText: {
    fontSize: 13,
    fontWeight: 'medium',
    color: color.hButtonText,
    textAlign: 'center',
    marginLeft: 2,
  },
  btHeaderText: {
    fontSize: 18,
    fontWeight: 'semibold',
    alignSelf: 'center',
    color: color.hText,
    marginTop: 14.5,
    marginBottom: 31,
  },
  btSubText: {
    fontSize: 13,
    fontWeight: 'medium',
    color: color.hText,
    marginHorizontal: 71.71,
  },
  btAmount: {
    fontSize: 13,
    fontWeight: 'semibold',
    color: color.hText,
    alignSelf: 'flex-end',
    marginHorizontal: 29,
  },
  btText: {
    fontSize: 10,
    fontWeight: 'medium',
    color: color.hDetails,
    marginHorizontal: 71.71,
  },
});
